# Generated by Django 2.0.5 on 2018-07-26 17:56

from django.db import migrations, models
import eventex.inscricoes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_auto_20180717_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=11, validators=[eventex.inscricoes.validators.valida_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
    ]
